# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Page:
  fields:
    list: permalink, title
    form: permalink, title, callout_text, body, seo_description, seo_keywords
    options:
      read_only: permalink
      tiny_mce:
        fields: body
        options:
          theme: advanced
          theme_advanced_toolbar_location: top
          content_css:
            - "/stylesheets/tinymce.css"
          theme_advanced_buttons1:
            - cut, copy, paste,|,bold,italic,|,link, unlink,|,formatselect,styleselect,|,bullist,numlist,|,code # FOR ADMIN TESTING,|,code
          theme_advanced_buttons2:
            - 
          theme_advanced_buttons3:
            - 
          theme_advanced_buttons4:
            - 
  order_by: permalink
  application: Content
  
  TypusUser:
  fields:
    list: email, role, status
    form: first_name, last_name, role, email, password, password_confirmation, language
    options:
      selectors: role, language
      booleans:
        status: Active, Inactive
  filters: status, role
  search: first_name, last_name, email, role
  application: Administration
  description: System Users Administration