# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Page: create, read, update, delete
  Post: create, read, update, delete
  TypusUser: create, read, update, delete

editor:
  Page: create, read, update
  Post: create, read, update, delete
