<?php
	if($_POST['submitted'] == "true" && $_POST['validated'] == ""){
			//The email address the message will be sent to
			$to = "theboss@screamingmonkeys.org"; 
			$nameto = "The Boss";
			$from = "theboss@screamingmonkeys.org";
			
			//The subject of the email you will receive;
			$subject = "A visitor to Screaming Monkeys has sent a message.";
			
			//Format the email			
			$name = $_POST['name'];
			$company = $_POST['company'];	
			
			$email = stripslashes($_POST['email']);
			$sent = false;
			
			$DOMAINS = array("aero",
							   "asia",
							   "biz",
							   "cat",
							   "com",
							   "coop",
							   "edu",
							   "gov",
							   "info",
							   "int",
							   "jobs",
							   "mil",
							   "mobi",
							   "museum",
							   "name",
							   "net",
							   "org",
							   "travel",
							   "ac",
							   "ae",
							   "af",
							   "ag",
							   "ai",
							   "al",
							   "am",
							   "an",
							   "ao",
							   "aq",
							   "ar",
							   "as",
							   "at",
							   "au",
							   "aw",
							   "ax",
							   "az",
							   "ba",
							   "bb",
							   "bd",
							   "be",
							   "bf",
							   "bg",
							   "bh",
							   "bi",
							   "bj",
							   "bm",
							   "bn",
							   "bo",
							   "br",
							   "bs",
							   "bt",
							   "bv",
							   "bw",
							   "by",
							   "bz",
							   "ca",
							   "cc",
							   "cd",
							   "cf",
							   "cg",
							   "ch",
							   "ci",
							   "ck",
							   "cl",
							   "cm",
							   "cn",
							   "co",
							   "cr",
							   "cs",
							   "cu",
							   "cv",
							   "cx",
							   "cy",
							   "cz",
							   "de",
							   "dj",
							   "dk",
							   "dm",
							   "do",
							   "dz",
							   "ec",
							   "ee",
							   "eg",
							   "eh",
							   "er",
							   "es",
							   "et",
							   "eu",
							   "fi",
							   "fj",
							   "fk",
							   "fm",
							   "fo",
							   "fr",
							   "ga",
							   "gb",
							   "gd",
							   "ge",
							   "gf",
							   "gg",
							   "gh",
							   "gi",
							   "gl",
							   "gm",
							   "gn",
							   "gp",
							   "gq",
							   "gr",
							   "gs",
							   "gt",
							   "gu",
							   "gw",
							   "gy",
							   "hk",
							   "hm",
							   "hn",
							   "hr",
							   "ht",
							   "hu",
							   "id",
							   "ie",
							   "il",
							   "im",
							   "in",
							   "io",
							   "iq",
							   "ir",
							   "is",
							   "it",
							   "je",
							   "jm",
							   "jo",
							   "jp",
							   "ke",
							   "kg",
							   "kh",
							   "ki",
							   "km",
							   "kn",
							   "kp",
							   "kr",
							   "kw",
							   "ky",
							   "kz",
							   "la",
							   "lb",
							   "lc",
							   "li",
							   "lk",
							   "lr",
							   "ls",
							   "lt",
							   "lu",
							   "lv",
							   "ly",
							   "ma",
							   "mc",
							   "md",
							   "me",
							   "mg",
							   "mh",
							   "mk",
							   "ml",
							   "mm",
							   "mn",
							   "mo",
							   "mp",
							   "mq",
							   "mr",
							   "ms",
							   "mt",
							   "mu",
							   "mv",
							   "mw",
							   "mx",
							   "my",
							   "mz",
							   "na",
							   "nc",
							   "ne",
							   "nf",
							   "ng",
							   "ni",
							   "nl",
							   "no",
							   "np",
							   "nr",
							   "nu",
							   "nz",
							   "om",
							   "pa",
							   "pe",
							   "pf",
							   "pg",
							   "ph",
							   "pk",
							   "pl",
							   "pm",
							   "pn",
							   "pr",
							   "ps",
							   "pt",
							   "pw",
							   "py",
							   "qa",
							   "re",
							   "ro",
							   "rs",
							   "ru",
							   "rw",
							   "sa",
							   "sb",
							   "sc",
							   "sd",
							   "se",
							   "sg",
							   "sh",
							   "si",
							   "sj",
							   "sk",
							   "sl",
							   "sm",
							   "sn",
							   "so",
							   "sr",
							   "st",
							   "su",
							   "sv",
							   "sy",
							   "sz",
							   "tc",
							   "td",
							   "tf",
							   "tg",
							   "th",
							   "tj",
							   "tk",
							   "tl",
							   "tm",
							   "tn",
							   "to",
							   "tp",
							   "tr",
							   "tt",
							   "tv",
							   "tw",
							   "tz",
							   "ua",
							   "ug",
							   "uk",
							   "um",
							   "us",
							   "uy",
							   "uz",
							   "va",
							   "vc",
							   "ve",
							   "vg",
							   "vi",
							   "vn",
							   "vu",
							   "wf",
							   "ws",
							   "ye",
							   "yt",
							   "yu",
							   "za",
							   "zm",
							   "zr",
							   "zq"
							  );
			
			//Validate Email
			if($name != ""){			
					$valid_ampersand = (substr_count($email, "@") == 1) ? true : false;			 //check for @ and make sure only one!
					$email_array = explode(".", $email);											 //explode string to loop through
					foreach($email_array as $value){												 //loop through string and check if valid domain used
						$valid_domain = in_array($value, $DOMAINS) ? true : false;
					}
					$valid_address = ($valid_ampersand && $valid_domain) ? true : false;			 //flag as valid address if domain and @ are valid
					
					if($valid_address){
						$url = ($_POST['url'] != "") ? "<a href='{$_POST['url']}'>".$_POST['url']."</a>" : "";
						$message = nl2br($_POST['message']);
						
						//Headers
						$headers = 'MIME-Version: 1.0' . "\n";
						$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\n";
						$headers .= "From: Screaming Monkeys <".$from.">\n";
						$headers .= "X-Sender: <".$from.">\n";
						$headers .= "Reply-To: ".$email."\n";
						$headers .= "Return-Path: ".$email."\n";
						$headers .= "X-Mailer: PHP\n"; // mailer
						$headers .= "X-Priority: 1\n"; // Urgent message!
						
						//Message Body
						$emailmessage = "<p><b>From:</b> ".$name." &nbsp;<<a href='mailto:".$email."'>".$email."</a>><br /><b>Company:</b> ".$company."<br /><b>URL:</b> ".$url."</p><hr /><p><h3>Visitor's Message</h3>".$message."</p><hr /><p><h3>Visitor Details:</h3><b>Browser:</b> ".$_SERVER['HTTP_USER_AGENT']."<br /><b>Http Referrer:</b> ".$_SERVER['HTTP_REFERER']."<br><b>Remote IP</b> ".$_SERVER['REMOTE_ADDR']."</p>";
						
						//SEND THE MESSAGE
						mail($to, $subject, $emailmessage, $headers) or die('error: failed to connect to mailserver');
						$sent = true;
					} else {
						//display mismatching address error
						$h1 = 'Please Try Again';
						$error = "<p style='color:#990000;'>You entered an invalid email address</p>";
						$data = $error.$data;
					}
			} else {
				//display empty name error
				$h1 = "Please Try Again";
				$error = "<p style='color:#990000;'>Please let us know what your name is.</p>";
				$data = $error.$data;
			}
		}
?>
